source "https://rubygems.org"

gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "sqlite3", ">= 1.4"
gem "puma", ">= 5.0"
gem "bootsnap", require: false

gem "graphql", "~> 2.4"

group :development, :test do
  gem "debug", platforms: %i[mri], require: "debug/prelude"
  gem "graphiql-rails"
  gem 'rack-cors'
end
